# Generated by Django 5.1.15 on 2026-07-25 23:41

from django.db import migrations, models

import core.id


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentPublic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("titre", models.CharField(max_length=250)),
                (
                    "nature",
                    models.CharField(
                        choices=[
                            ("LOI", "Loi"),
                            ("DECRET", "Décret"),
                            ("ARRETE", "Arrêté"),
                            ("AVIS_CONCOURS", "Avis de concours"),
                            ("COMMUNIQUE", "Communiqué"),
                            ("RAPPORT", "Rapport"),
                        ],
                        max_length=20,
                    ),
                ),
                ("numero", models.CharField(blank=True, max_length=100)),
                ("date_texte", models.DateField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[("EN_VIGUEUR", "En vigueur"), ("ABROGE", "Abrogé")],
                        default="EN_VIGUEUR",
                        max_length=20,
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Regroupement portail : textes-juridiques, concours, statistiques…",
                        max_length=60,
                    ),
                ),
                (
                    "fichier_url",
                    models.URLField(
                        blank=True, help_text="Placeholder — stockage MinIO au Bloc B/C."
                    ),
                ),
                ("publie", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "documents_publics",
                "ordering": ["-date_texte", "-cree_le"],
            },
        ),
    ]
