# Generated by Django 5.1.15 on 2026-07-26 21:33

import django.db.models.deletion
from django.db import migrations, models

import apps.mediatheque.models
import core.id


class Migration(migrations.Migration):

    dependencies = [
        ("mediatheque", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Galerie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=80, unique=True)),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Galeries",
                "db_table": "galeries",
                "ordering": ["titre"],
            },
        ),
        migrations.CreateModel(
            name="MediaGalerie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("IMAGE", "Image"), ("VIDEO", "Vidéo (lien incorporé)")],
                        max_length=10,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to=apps.mediatheque.models.chemin_media_galerie
                    ),
                ),
                ("video_url", models.URLField(blank=True)),
                ("legende", models.CharField(blank=True, max_length=200)),
                ("ordre", models.PositiveIntegerField(default=0)),
                ("publie", models.BooleanField(default=True)),
                (
                    "galerie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medias",
                        to="mediatheque.galerie",
                    ),
                ),
            ],
            options={
                "db_table": "medias_galerie",
                "ordering": ["ordre", "cree_le"],
            },
        ),
    ]
