# Generated by Django 5.1.15 on 2026-07-27 12:20

from django.db import migrations, models

import apps.mediatheque.models


class Migration(migrations.Migration):

    dependencies = [
        ("mediatheque", "0003_galeries_connues"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentpublic",
            name="fichier_url",
        ),
        migrations.AddField(
            model_name="documentpublic",
            name="fichier",
            field=models.FileField(
                blank=True, upload_to=apps.mediatheque.models.chemin_document_public
            ),
        ),
    ]
