# Generated by Django 5.1.15 on 2026-07-27 23:56

import django.db.models.deletion
from django.db import migrations, models

import core.id


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "canal",
                    models.CharField(choices=[("EMAIL", "E-mail"), ("SMS", "SMS")], max_length=10),
                ),
                ("destinataire", models.CharField(max_length=200)),
                ("sujet", models.CharField(blank=True, max_length=200)),
                ("contenu", models.TextField()),
                (
                    "statut",
                    models.CharField(
                        choices=[("ENVOYE", "Envoyé"), ("ECHEC", "Échec")], max_length=10
                    ),
                ),
                ("object_id", models.UUIDField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-cree_le"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"], name="notificatio_content_3c688e_idx"
                    )
                ],
            },
        ),
    ]
