# Generated by Django 5.1.15 on 2026-07-25 12:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.comptes.managers
import core.id


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Perimetre",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("NATIONAL", "National"),
                            ("DIRECTION", "Direction"),
                            ("ETABLISSEMENT", "Établissement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("libelle", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "perimetres",
                "ordering": ["libelle"],
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.SlugField(
                        help_text="Format conseillé : module:action.", max_length=100, unique=True
                    ),
                ),
                ("libelle", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("categorie", models.CharField(blank=True, db_index=True, max_length=50)),
            ],
            options={
                "db_table": "permissions",
                "ordering": ["categorie", "code"],
            },
        ),
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("nom", models.CharField(max_length=150)),
                ("prenom", models.CharField(max_length=150)),
                ("matricule", models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ("telephone", models.CharField(blank=True, max_length=20)),
                (
                    "est_agent_interne",
                    models.BooleanField(
                        default=False,
                        help_text="Compte agent DGAP : MFA obligatoire, accès intranet/back-office.",
                    ),
                ),
                (
                    "est_superviseur_national",
                    models.BooleanField(
                        default=False,
                        help_text="Bypass des vérifications de périmètre (direction générale, audit).",
                    ),
                ),
                ("mfa_active", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now)),
                ("derniere_connexion_reussie", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "utilisateurs",
                "ordering": ["nom", "prenom"],
            },
            managers=[
                ("objects", apps.comptes.managers.GestionnaireUtilisateur()),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("libelle", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True, related_name="roles", to="comptes.permission"
                    ),
                ),
            ],
            options={
                "db_table": "roles",
                "ordering": ["libelle"],
            },
        ),
        migrations.CreateModel(
            name="AttributionPermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "motif",
                    models.CharField(
                        blank=True, help_text="Raison de l'exception (traçabilité).", max_length=255
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                ("date_debut", models.DateField(default=django.utils.timezone.now)),
                ("date_fin", models.DateField(blank=True, null=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributions_permission",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "perimetre",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vide = portée nationale.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attributions_permission",
                        to="comptes.perimetre",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributions_directes",
                        to="comptes.permission",
                    ),
                ),
            ],
            options={
                "db_table": "attributions_permission",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("utilisateur", "permission", "perimetre"),
                        name="uniq_attribution_utilisateur_permission_perimetre",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AffectationRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("actif", models.BooleanField(default=True)),
                ("date_debut", models.DateField(default=django.utils.timezone.now)),
                ("date_fin", models.DateField(blank=True, null=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affectations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "perimetre",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vide = portée nationale (réservé aux rôles habilités).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="affectations_role",
                        to="comptes.perimetre",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="affectations",
                        to="comptes.role",
                    ),
                ),
            ],
            options={
                "db_table": "affectations_role",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("utilisateur", "role", "perimetre"),
                        name="uniq_affectation_utilisateur_role_perimetre",
                    )
                ],
            },
        ),
    ]
