# Generated by Django 5.1.15 on 2026-07-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="compte_demonstration",
            field=models.BooleanField(
                default=False,
                help_text="Compte de démonstration (script de seed) : dispensé du MFA pour rester utilisable immédiatement par login/mot de passe. Jamais vrai en production.",
            ),
        ),
    ]
