# Generated by Django 5.1.15 on 2026-07-28 18:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0002_utilisateur_compte_demonstration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affectationrole",
            name="date_debut",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="attributionpermission",
            name="date_debut",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
