# Generated by Django 5.1.15 on 2026-07-28 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.id


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EchangeExterne",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "systeme",
                    models.CharField(
                        choices=[
                            ("CHAINE_JUDICIAIRE", "Chaîne judiciaire (Ministère de la Justice)"),
                            ("FORCES_SECURITE", "Forces de sécurité (Police/Gendarmerie)"),
                            ("TRESOR", "Trésor public"),
                            ("PLATEFORME_GOUVERNEMENTALE", "Plateforme gouvernementale"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("SORTANT", "Sortant"), ("ENTRANT", "Entrant")], max_length=10
                    ),
                ),
                (
                    "type_echange",
                    models.CharField(
                        help_text="Ex. « notification d'écrou », « rapprochement quotidien ».",
                        max_length=150,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("SUCCES", "Succès"), ("ECHEC", "Échec")], max_length=10
                    ),
                ),
                ("empreinte_charge", models.CharField(blank=True, max_length=64)),
                ("detail", models.JSONField(blank=True, default=dict)),
                (
                    "acteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Échange externe",
                "db_table": "echanges_externes",
                "ordering": ["-cree_le"],
            },
        ),
    ]
