# Generated by Django 5.1.15 on 2026-07-28 15:10

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models

import core.id


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comptes", "0002_utilisateur_compte_demonstration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DossierAgent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("supprime_le", models.DateTimeField(blank=True, editable=False, null=True)),
                ("corps", models.CharField(blank=True, db_index=True, max_length=150)),
                ("grade", models.CharField(blank=True, db_index=True, max_length=150)),
                (
                    "position_administrative",
                    models.CharField(
                        choices=[
                            ("ACTIVITE", "Activité"),
                            ("DETACHEMENT", "Détachement"),
                            ("DISPONIBILITE", "Disponibilité"),
                            ("CONGE_LONGUE_DUREE", "Congé de longue durée"),
                            ("RETRAITE", "Retraite"),
                        ],
                        default="ACTIVITE",
                        max_length=20,
                    ),
                ),
                (
                    "situation_familiale",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CELIBATAIRE", "Célibataire"),
                            ("MARIE", "Marié(e)"),
                            ("DIVORCE", "Divorcé(e)"),
                            ("VEUF", "Veuf(ve)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_entree_service", models.DateField(blank=True, null=True)),
                ("diplomes", models.TextField(blank=True, help_text="Un diplôme par ligne.")),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "utilisateur",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dossier_rh",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dossier agent (RH)",
                "db_table": "dossiers_agent_rh",
            },
            managers=[
                ("objets", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="DemandeRH",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("supprime_le", models.DateTimeField(blank=True, editable=False, null=True)),
                ("numero", models.CharField(editable=False, max_length=30, unique=True)),
                (
                    "type_demande",
                    models.CharField(
                        choices=[
                            ("CONGE", "Congé"),
                            ("PERMISSION_ABSENCE", "Permission d'absence"),
                            ("ATTESTATION_TRAVAIL", "Attestation de travail"),
                            ("AUTRE", "Autre demande"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("SOUMISE", "Soumise"),
                            ("VALIDEE", "Validée"),
                            ("REJETEE", "Rejetée"),
                            ("ANNULEE", "Annulée"),
                        ],
                        default="SOUMISE",
                        max_length=15,
                    ),
                ),
                (
                    "date_debut",
                    models.DateField(
                        blank=True, help_text="Congé/permission : premier jour.", null=True
                    ),
                ),
                ("date_fin", models.DateField(blank=True, null=True)),
                ("motif", models.TextField(blank=True)),
                ("date_validation", models.DateTimeField(blank=True, null=True)),
                ("motif_rejet", models.CharField(blank=True, max_length=300)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demandes",
                        to="rh.dossieragent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande administrative (RH)",
                "db_table": "demandes_rh",
                "ordering": ["-cree_le"],
            },
            managers=[
                ("objets", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="AffectationAgent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("fonction", models.CharField(blank=True, max_length=200)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField(blank=True, null=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "perimetre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="comptes.perimetre",
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affectations",
                        to="rh.dossieragent",
                    ),
                ),
            ],
            options={
                "db_table": "affectations_agent_rh",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="ActeCarriere",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("supprime_le", models.DateTimeField(blank=True, editable=False, null=True)),
                ("numero", models.CharField(editable=False, max_length=30, unique=True)),
                (
                    "type_acte",
                    models.CharField(
                        choices=[
                            ("TITULARISATION", "Titularisation"),
                            ("AVANCEMENT", "Avancement"),
                            ("MUTATION", "Mutation"),
                            ("DETACHEMENT", "Détachement"),
                            ("DISPONIBILITE", "Disponibilité"),
                            ("RETRAITE", "Retraite"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("SOUMIS", "Soumis"),
                            ("VALIDE", "Validé"),
                            ("REJETE", "Rejeté"),
                        ],
                        default="BROUILLON",
                        max_length=15,
                    ),
                ),
                ("date_effet", models.DateField()),
                ("motif", models.TextField(blank=True)),
                ("nouveau_grade", models.CharField(blank=True, max_length=150)),
                ("nouvelle_fonction", models.CharField(blank=True, max_length=200)),
                ("date_validation", models.DateTimeField(blank=True, null=True)),
                ("motif_rejet", models.CharField(blank=True, max_length=300)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nouveau_perimetre",
                    models.ForeignKey(
                        blank=True,
                        help_text="Renseigné pour une mutation.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="comptes.perimetre",
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actes_carriere",
                        to="rh.dossieragent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acte de carrière",
                "db_table": "actes_carriere_rh",
                "ordering": ["-cree_le"],
            },
            managers=[
                ("objets", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="SoldeConge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("annee", models.PositiveSmallIntegerField()),
                ("jours_acquis", models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ("jours_pris", models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soldes_conge",
                        to="rh.dossieragent",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "soldes_conge_rh",
                "ordering": ["-annee"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dossier", "annee"), name="uniq_solde_conge_dossier_annee"
                    )
                ],
            },
        ),
    ]
