# Generated by Django 5.1.15 on 2026-07-27 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.id


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comptes", "0002_utilisateur_compte_demonstration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteDeService",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("titre", models.CharField(max_length=250)),
                ("contenu", models.TextField()),
                ("accuse_lecture_requis", models.BooleanField(default=False)),
                ("publie", models.BooleanField(default=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "perimetre_cible",
                    models.ForeignKey(
                        help_text="Diffusion : périmètre national pour toute la DGAP, sinon une direction ou un établissement précis.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notes_de_service",
                        to="comptes.perimetre",
                    ),
                ),
            ],
            options={
                "db_table": "notes_de_service",
                "ordering": ["-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="AccuseLectureNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accuses_lecture_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accuses_lecture",
                        to="intranet.notedeservice",
                    ),
                ),
            ],
            options={
                "db_table": "accuses_lecture_notes",
                "ordering": ["-cree_le"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("note", "utilisateur"), name="uniq_accuse_lecture_note"
                    )
                ],
            },
        ),
    ]
