# Generated by Django 5.1.15 on 2026-07-25 23:41

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models

import core.id


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rubrique",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=80, unique=True)),
                ("titre", models.CharField(max_length=150)),
                ("ordre", models.PositiveIntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enfants",
                        to="contenus.rubrique",
                    ),
                ),
            ],
            options={
                "db_table": "rubriques",
                "ordering": ["ordre", "titre"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("supprime_le", models.DateTimeField(blank=True, editable=False, null=True)),
                ("titre", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("contenu", models.TextField(blank=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("RELECTURE", "En relecture"),
                            ("VALIDE", "Validé"),
                            ("PUBLIE", "Publié"),
                            ("ARCHIVE", "Archivé"),
                        ],
                        default="BROUILLON",
                        max_length=20,
                    ),
                ),
                ("meta_titre", models.CharField(blank=True, max_length=200)),
                ("meta_description", models.CharField(blank=True, max_length=300)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rubrique",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pages",
                        to="contenus.rubrique",
                    ),
                ),
            ],
            options={
                "db_table": "pages",
                "ordering": ["titre"],
            },
            managers=[
                ("objets", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("supprime_le", models.DateTimeField(blank=True, editable=False, null=True)),
                ("titre", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                (
                    "chapo",
                    models.TextField(blank=True, help_text="Résumé affiché dans les listes."),
                ),
                ("contenu", models.TextField(blank=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("RELECTURE", "En relecture"),
                            ("VALIDE", "Validé"),
                            ("PUBLIE", "Publié"),
                            ("ARCHIVE", "Archivé"),
                        ],
                        default="BROUILLON",
                        max_length=20,
                    ),
                ),
                ("date_publication", models.DateTimeField(blank=True, null=True)),
                (
                    "image_url",
                    models.URLField(
                        blank=True, help_text="Placeholder — médiathèque MinIO au Bloc B/C."
                    ),
                ),
                ("meta_titre", models.CharField(blank=True, max_length=200)),
                ("meta_description", models.CharField(blank=True, max_length=300)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rubrique",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="contenus.rubrique",
                    ),
                ),
            ],
            options={
                "db_table": "articles",
                "ordering": ["-date_publication", "-cree_le"],
            },
            managers=[
                ("objets", django.db.models.manager.Manager()),
            ],
        ),
    ]
