# Generated by Django 5.1.15 on 2026-07-26 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.id


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("contenus", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=60, unique=True)),
                ("libelle", models.CharField(max_length=150)),
            ],
            options={
                "db_table": "menus",
                "ordering": ["libelle"],
            },
        ),
        migrations.CreateModel(
            name="ElementMenu",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("libelle", models.CharField(max_length=150)),
                (
                    "url",
                    models.CharField(
                        blank=True, help_text="URL directe, si non lié à une page.", max_length=300
                    ),
                ),
                ("ordre", models.PositiveIntegerField(default=0)),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="elements_menu",
                        to="contenus.page",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enfants",
                        to="contenus.elementmenu",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elements",
                        to="contenus.menu",
                    ),
                ),
            ],
            options={
                "db_table": "elements_menu",
                "ordering": ["ordre"],
            },
        ),
        migrations.CreateModel(
            name="VersionContenu",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("object_id", models.UUIDField()),
                ("numero", models.PositiveIntegerField()),
                ("instantane", models.JSONField(default=dict)),
                ("commentaire", models.CharField(blank=True, max_length=300)),
                (
                    "auteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "versions_contenu",
                "ordering": ["-numero"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"], name="versions_co_content_45a5c6_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content_type", "object_id", "numero"),
                        name="uniq_version_par_contenu",
                    )
                ],
            },
        ),
    ]
