# Generated by Django 5.1.15 on 2026-07-26 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenus", "0002_menu_elementmenu_versioncontenu"),
        ("mediatheque", "0002_galerie_mediagalerie"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="galerie",
            field=models.ForeignKey(
                blank=True,
                help_text="Galerie d'images/vidéos complémentaires affichée sous l'article.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="mediatheque.galerie",
            ),
        ),
    ]
