# Generated by Django 5.1.15 on 2026-07-27 12:20

from django.db import migrations, models

import apps.contenus.models


class Migration(migrations.Migration):

    dependencies = [
        ("contenus", "0003_article_galerie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="image_url",
        ),
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True, upload_to=apps.contenus.models.chemin_image_article
            ),
        ),
    ]
