# Generated by Django 5.1.15 on 2026-07-28 00:51

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models

import apps.ged.models
import core.id


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comptes", "0002_utilisateur_compte_demonstration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("supprime_le", models.DateTimeField(blank=True, editable=False, null=True)),
                ("titre", models.CharField(max_length=250)),
                (
                    "nature",
                    models.CharField(
                        choices=[
                            ("ADMINISTRATIF", "Administratif"),
                            ("JURIDIQUE", "Juridique"),
                            ("TECHNIQUE", "Technique"),
                        ],
                        max_length=15,
                    ),
                ),
                ("categorie", models.CharField(blank=True, db_index=True, max_length=150)),
                ("fichier", models.FileField(upload_to=apps.ged.models.chemin_document_ged)),
                ("empreinte_sha256", models.CharField(blank=True, editable=False, max_length=64)),
                ("contenu_ocr", models.TextField(blank=True)),
                (
                    "statut_ocr",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("TRAITE", "Traité"),
                            ("ECHEC", "Échec"),
                        ],
                        default="EN_ATTENTE",
                        max_length=15,
                    ),
                ),
                (
                    "statut_cycle_vie",
                    models.CharField(
                        choices=[
                            ("ACTIF", "Actif"),
                            ("ARCHIVE", "Archivé"),
                            ("DETRUIT", "Détruit"),
                        ],
                        default="ACTIF",
                        max_length=15,
                    ),
                ),
                ("duree_conservation_mois", models.PositiveIntegerField(blank=True, null=True)),
                ("date_destruction_prevue", models.DateField(blank=True, null=True)),
                (
                    "gel_juridique",
                    models.BooleanField(
                        default=False,
                        help_text="Suspend toute destruction tant que ce gel n'est pas levé.",
                    ),
                ),
                ("verrouille_le", models.DateTimeField(blank=True, null=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "perimetre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_ged",
                        to="comptes.perimetre",
                    ),
                ),
                (
                    "verrouille_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document (GED)",
                "db_table": "documents_ged",
                "ordering": ["-cree_le"],
            },
            managers=[
                ("objets", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="LienPartage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "jeton",
                    models.CharField(
                        default=apps.ged.models.generer_jeton_partage,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("expire_le", models.DateTimeField()),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liens_partage",
                        to="ged.document",
                    ),
                ),
            ],
            options={
                "db_table": "liens_partage_ged",
                "ordering": ["-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="VersionDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("numero", models.PositiveIntegerField()),
                ("fichier", models.FileField(upload_to=apps.ged.models.chemin_version_document)),
                ("empreinte_sha256", models.CharField(blank=True, max_length=64)),
                ("commentaire", models.CharField(blank=True, max_length=300)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="ged.document",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "versions_document_ged",
                "ordering": ["-numero"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "numero"), name="uniq_version_document_ged"
                    )
                ],
            },
        ),
    ]
