# Generated by Django 5.1.15 on 2026-07-25 12:11

import django.db.models.manager
from django.db import migrations, models

import core.id


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JournalAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CONSULTER", "Consulter"),
                            ("CREER", "Créer"),
                            ("MODIFIER", "Modifier"),
                            ("VALIDER", "Valider"),
                            ("REJETER", "Rejeter"),
                            ("EXPORTER", "Exporter"),
                            ("ACCES_REFUSE", "Accès refusé"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ressource_type", models.CharField(max_length=100)),
                ("ressource_id", models.CharField(blank=True, max_length=64)),
                ("horodatage", models.DateTimeField(auto_now_add=True)),
                ("adresse_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("agent_utilisateur", models.TextField(blank=True)),
                ("correlation_id", models.CharField(blank=True, max_length=64)),
                ("detail", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "journal_actions",
                "ordering": ["-horodatage"],
            },
            managers=[
                ("objets", django.db.models.manager.Manager()),
            ],
        ),
    ]
