# Generated by Django 5.1.15 on 2026-07-25 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("audit", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="journalaction",
            name="acteur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="journalaction",
            index=models.Index(
                fields=["ressource_type", "ressource_id"], name="journal_act_ressour_87fde7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalaction",
            index=models.Index(
                fields=["acteur", "horodatage"], name="journal_act_acteur__0e9724_idx"
            ),
        ),
    ]
