# Generated by Django 5.1.15 on 2026-07-27 16:26

from django.db import migrations, models

import apps.boutique.models
import core.id


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProduitBoutique",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("nom", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                (
                    "categorie",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Regroupement boutique, ex. Jus locaux, Produits d'entretien, Mobilier.",
                        max_length=80,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "prix",
                    models.DecimalField(
                        decimal_places=0, help_text="Montant en FCFA.", max_digits=10
                    ),
                ),
                (
                    "prix_promotionnel",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="Prix réduit affiché à la place de `prix`, si renseigné (FCFA).",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to=apps.boutique.models.chemin_image_produit
                    ),
                ),
                ("disponible", models.BooleanField(default=True)),
                ("ordre", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "produits_boutique",
                "ordering": ["ordre", "nom"],
            },
        ),
    ]
