# Generated by Django 5.1.15 on 2026-07-26 14:58

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models

import apps.visites.models
import core.id


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("etablissements", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreneauVisite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("jour", models.DateField()),
                ("heure_debut", models.TimeField()),
                ("heure_fin", models.TimeField()),
                ("capacite", models.PositiveIntegerField(default=10)),
                (
                    "etablissement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creneaux_visite",
                        to="etablissements.etablissement",
                    ),
                ),
            ],
            options={
                "db_table": "creneaux_visite",
                "ordering": ["jour", "heure_debut"],
            },
        ),
        migrations.CreateModel(
            name="DemandeVisite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("supprime_le", models.DateTimeField(blank=True, editable=False, null=True)),
                ("numero_suivi", models.CharField(editable=False, max_length=30, unique=True)),
                ("code_suivi", models.CharField(editable=False, max_length=10)),
                ("visiteur_nom", models.CharField(max_length=150)),
                ("visiteur_prenom", models.CharField(max_length=150)),
                ("visiteur_email", models.EmailField(max_length=254)),
                ("visiteur_telephone", models.CharField(max_length=30)),
                ("lien_parente", models.CharField(max_length=100)),
                ("detenu_nom_declare", models.CharField(max_length=150)),
                ("detenu_prenom_declare", models.CharField(max_length=150)),
                ("date_souhaitee", models.DateField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("SOUMISE", "Soumise"),
                            ("EN_INSTRUCTION", "En instruction"),
                            ("PIECES_MANQUANTES", "Pièces manquantes"),
                            ("VALIDEE", "Validée"),
                            ("REJETEE", "Rejetée"),
                            ("PERMIS_DELIVRE", "Permis délivré"),
                        ],
                        default="SOUMISE",
                        max_length=20,
                    ),
                ),
                ("motif_rejet", models.TextField(blank=True)),
                ("date_instruction", models.DateTimeField(blank=True, null=True)),
                (
                    "cle_idempotence",
                    models.CharField(blank=True, max_length=80, null=True, unique=True),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creneau",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="demandes",
                        to="visites.creneauvisite",
                    ),
                ),
                (
                    "etablissement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="demandes_visite",
                        to="etablissements.etablissement",
                    ),
                ),
                (
                    "instructeur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "demandes_visite",
                "ordering": ["-cree_le"],
            },
            managers=[
                ("objets", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="PermisVisite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("numero_permis", models.CharField(editable=False, max_length=40, unique=True)),
                (
                    "charge_qr_jws",
                    models.TextField(
                        editable=False, help_text="Charge signée (JWS) encodée dans le QR."
                    ),
                ),
                ("valide_jusqu_au", models.DateField()),
                ("revoque", models.BooleanField(default=False)),
                (
                    "demande",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permis",
                        to="visites.demandevisite",
                    ),
                ),
            ],
            options={
                "db_table": "permis_visite",
                "ordering": ["-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="PieceJointeVisite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "type_piece",
                    models.CharField(
                        choices=[
                            ("CNI_VISITEUR", "Pièce d'identité du visiteur"),
                            ("PERMIS_COMMUNIQUER", "Permis de communiquer existant"),
                            ("AUTRE", "Autre document"),
                        ],
                        max_length=30,
                    ),
                ),
                ("fichier", models.FileField(upload_to=apps.visites.models.chemin_piece_jointe)),
                ("empreinte_sha256", models.CharField(blank=True, editable=False, max_length=64)),
                (
                    "statut_controle",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente de contrôle"),
                            ("LISIBLE", "Lisible"),
                            ("ILLISIBLE", "Illisible — à representer"),
                        ],
                        default="EN_ATTENTE",
                        max_length=20,
                    ),
                ),
                (
                    "demande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pieces",
                        to="visites.demandevisite",
                    ),
                ),
            ],
            options={
                "db_table": "pieces_jointes_visite",
                "ordering": ["-cree_le"],
            },
        ),
    ]
