# Redirection HTTPS obligatoire (§9.3) pour les 4 sous-domaines, dev et prod.
server {
    listen 80;
    server_name
        www.administrationpenitentiaire.sn administrationpenitentiaire.sn www.localhost
        demarches.administrationpenitentiaire.sn demarches.localhost
        intranet.administrationpenitentiaire.sn intranet.localhost
        admin.administrationpenitentiaire.sn admin.localhost;

    location / {
        return 301 https://$host$request_uri;
    }
}
