# Generated by Django 5.1.15 on 2026-07-28 00:22

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.courrier.models
import core.id


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comptes", "0002_utilisateur_compte_demonstration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourrierEntrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("supprime_le", models.DateTimeField(blank=True, editable=False, null=True)),
                ("numero", models.CharField(editable=False, max_length=30, unique=True)),
                ("expediteur", models.CharField(max_length=200)),
                ("objet", models.CharField(max_length=300)),
                ("date_reception", models.DateField(default=django.utils.timezone.now)),
                (
                    "confidentialite",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("CONFIDENTIEL", "Confidentiel"),
                            ("SECRET", "Secret"),
                        ],
                        default="NORMAL",
                        max_length=15,
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        blank=True, upload_to=apps.courrier.models.chemin_courrier_entrant
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ENREGISTRE", "Enregistré"),
                            ("AFFECTE", "Affecté"),
                            ("EN_TRAITEMENT", "En traitement"),
                            ("TRAITE", "Traité"),
                            ("CLOS", "Clos"),
                        ],
                        default="ENREGISTRE",
                        max_length=20,
                    ),
                ),
                ("delai_reponse", models.DateField(blank=True, null=True)),
                ("instructions", models.TextField(blank=True)),
                (
                    "agent_affecte",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "perimetre_affecte",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courriers_entrants",
                        to="comptes.perimetre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Courrier entrant",
                "db_table": "courriers_entrants",
                "ordering": ["-cree_le"],
            },
            managers=[
                ("objets", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="AffectationCourrier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("instructions", models.TextField(blank=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "perimetre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="comptes.perimetre",
                    ),
                ),
                (
                    "courrier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affectations",
                        to="courrier.courrierentrant",
                    ),
                ),
            ],
            options={
                "db_table": "affectations_courrier",
                "ordering": ["-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="ReponseCourrier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("contenu", models.TextField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("VISE", "Visé"),
                            ("VALIDE", "Validé"),
                            ("EXPEDIE", "Expédié"),
                        ],
                        default="BROUILLON",
                        max_length=15,
                    ),
                ),
                ("date_signature", models.DateTimeField(blank=True, null=True)),
                (
                    "courrier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reponses",
                        to="courrier.courrierentrant",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "signataire",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reponses_courrier",
                "ordering": ["-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="CourrierSortant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("supprime_le", models.DateTimeField(blank=True, editable=False, null=True)),
                ("numero", models.CharField(editable=False, max_length=30, unique=True)),
                ("destinataire", models.CharField(max_length=200)),
                ("objet", models.CharField(max_length=300)),
                ("date_envoi", models.DateField(blank=True, null=True)),
                (
                    "fichier",
                    models.FileField(
                        blank=True, upload_to=apps.courrier.models.chemin_courrier_sortant
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ENREGISTRE", "Enregistré"),
                            ("EXPEDIE", "Expédié"),
                            ("ACCUSE_RECU", "Accusé de réception reçu"),
                        ],
                        default="ENREGISTRE",
                        max_length=15,
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "perimetre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="comptes.perimetre",
                    ),
                ),
                (
                    "reponse_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courriers_sortants",
                        to="courrier.reponsecourrier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Courrier sortant",
                "db_table": "courriers_sortants",
                "ordering": ["-cree_le"],
            },
            managers=[
                ("objets", django.db.models.manager.Manager()),
            ],
        ),
    ]
