# Generated by Django 5.1.15 on 2026-07-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courrier", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="courrierentrant",
            name="expediteur_email",
            field=models.EmailField(
                blank=True,
                help_text="Si connu — permet l'envoi automatique de la réponse par e-mail à l'expédition (courrier postal/institutionnel sans e-mail : laisser vide).",
                max_length=254,
            ),
        ),
    ]
