# Generated by Django 5.1.15 on 2026-07-25 23:41

from django.db import migrations, models

import core.id


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=40, unique=True)),
                ("nom", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "regions",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="TypeEtablissement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=60, unique=True)),
                ("libelle", models.CharField(max_length=150)),
            ],
            options={
                "db_table": "types_etablissement",
                "ordering": ["libelle"],
            },
        ),
        migrations.CreateModel(
            name="DirectionRegionale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=60, unique=True)),
                ("nom", models.CharField(max_length=150)),
                ("directeur_nom", models.CharField(blank=True, max_length=150)),
                ("directeur_email", models.EmailField(blank=True, max_length=254)),
                ("directeur_telephone", models.CharField(blank=True, max_length=30)),
                (
                    "regions",
                    models.ManyToManyField(
                        blank=True, related_name="directions_regionales", to="referentiels.region"
                    ),
                ),
            ],
            options={
                "verbose_name": "Direction régionale (IRAP)",
                "verbose_name_plural": "Directions régionales (IRAP)",
                "db_table": "directions_regionales",
                "ordering": ["nom"],
            },
        ),
    ]
