# Generated by Django 5.1.15 on 2026-07-27 11:32

import django.db.models.deletion
from django.db import migrations, models

import core.id


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("object_id", models.UUIDField()),
                ("reference", models.CharField(editable=False, max_length=40, unique=True)),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=0, help_text="Montant en FCFA.", max_digits=10
                    ),
                ),
                (
                    "moyen",
                    models.CharField(
                        choices=[
                            ("MOCK", "Simulation (aucun opérateur réel)"),
                            ("ORANGE_MONEY", "Orange Money"),
                            ("WAVE", "Wave"),
                        ],
                        default="MOCK",
                        max_length=20,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("PAYE", "Payé"),
                            ("ECHEC", "Échec"),
                        ],
                        default="EN_ATTENTE",
                        max_length=20,
                    ),
                ),
                ("paye_le", models.DateTimeField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
            ],
            options={
                "db_table": "paiements",
                "ordering": ["-cree_le"],
            },
        ),
    ]
