# Generated by Django 5.1.15 on 2026-07-25 23:41

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models

import core.id


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("question", models.CharField(max_length=300)),
                ("reponse", models.TextField()),
                ("categorie", models.CharField(blank=True, db_index=True, max_length=100)),
                ("ordre", models.PositiveIntegerField(default=0)),
                ("publie", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQ",
                "db_table": "faq",
                "ordering": ["categorie", "ordre"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("supprime_le", models.DateTimeField(blank=True, editable=False, null=True)),
                ("numero_ticket", models.CharField(editable=False, max_length=20, unique=True)),
                ("nom", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("telephone", models.CharField(blank=True, max_length=30)),
                ("sujet", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("NOUVEAU", "Nouveau"),
                            ("EN_TRAITEMENT", "En traitement"),
                            ("TRAITE", "Traité"),
                        ],
                        default="NOUVEAU",
                        max_length=20,
                    ),
                ),
                ("reponse", models.TextField(blank=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "contacts",
                "ordering": ["-cree_le"],
            },
            managers=[
                ("objets", django.db.models.manager.Manager()),
            ],
        ),
    ]
