# Generated by Django 5.1.15 on 2026-07-28 19:03

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.detenus.models
import core.champs
import core.id


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("etablissements", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonneDetenue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("supprime_le", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "numero_ecrou",
                    models.CharField(db_index=True, editable=False, max_length=30, unique=True),
                ),
                ("nom", core.champs.ChampChiffre(editable=True)),
                ("prenom", core.champs.ChampChiffre(editable=True)),
                ("date_naissance", models.DateField()),
                (
                    "date_naissance_approximative",
                    models.BooleanField(
                        default=False,
                        help_text="Coché lorsque la date de naissance n'est pas certaine.",
                    ),
                ),
                (
                    "sexe",
                    models.CharField(choices=[("M", "Masculin"), ("F", "Féminin")], max_length=1),
                ),
                (
                    "situation_penale",
                    models.CharField(
                        choices=[
                            ("PREVENU", "Prévenu"),
                            ("CONDAMNE", "Condamné"),
                            ("CONTRAINTE_PAR_CORPS", "Contrainte par corps"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "regime",
                    models.CharField(
                        choices=[
                            ("ORDINAIRE", "Ordinaire"),
                            ("SEMI_LIBERTE", "Semi-liberté"),
                            ("QUARTIER_HAUTE_SECURITE", "Quartier de haute sécurité"),
                        ],
                        default="ORDINAIRE",
                        max_length=30,
                    ),
                ),
                (
                    "statut_dossier",
                    models.CharField(
                        choices=[
                            ("ECROUE", "Écroué"),
                            ("LIBERE", "Libéré"),
                            ("TRANSFERE", "Transféré"),
                            ("EVADE", "Évadé"),
                        ],
                        default="ECROUE",
                        max_length=15,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to=apps.detenus.models.chemin_photo_detenu
                    ),
                ),
                ("date_ecrou", models.DateField()),
                (
                    "date_liberation_prevue",
                    models.DateField(
                        blank=True,
                        help_text="Saisie et mise à jour manuelles par un agent habilité — jamais calculée automatiquement (voir docstring du module).",
                        null=True,
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "etablissement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="personnes_detenues",
                        to="etablissements.etablissement",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Personne détenue",
                "verbose_name_plural": "Personnes détenues",
                "db_table": "personnes_detenues",
                "ordering": ["-date_ecrou"],
            },
            managers=[
                ("objets", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Mouvement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "type_mouvement",
                    models.CharField(
                        choices=[
                            ("ECROU", "Écrou"),
                            ("LEVEE_ECROU", "Levée d'écrou"),
                            ("TRANSFERT", "Transfert"),
                            ("EXTRACTION", "Extraction"),
                            ("HOSPITALISATION", "Hospitalisation"),
                            ("PERMISSION_SORTIR", "Permission de sortir"),
                            ("EVASION", "Évasion"),
                            ("REINTEGRATION", "Réintégration"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_mouvement", models.DateTimeField(default=django.utils.timezone.now)),
                ("motif", models.TextField(blank=True)),
                (
                    "piece_justificative",
                    models.FileField(
                        blank=True, upload_to=apps.detenus.models.chemin_piece_mouvement
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "etablissement_destination",
                    models.ForeignKey(
                        blank=True,
                        help_text="Renseigné pour un transfert.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="etablissements.etablissement",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "personne",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mouvements",
                        to="detenus.personnedetenue",
                    ),
                ),
            ],
            options={
                "db_table": "mouvements_detenus",
                "ordering": ["-date_mouvement"],
            },
        ),
    ]
