# Generated by Django 5.1.15 on 2026-07-25 23:41

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models

import core.id


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("referentiels", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Etablissement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("supprime_le", models.DateTimeField(blank=True, editable=False, null=True)),
                ("nom", models.CharField(max_length=200)),
                ("code", models.SlugField(max_length=80, unique=True)),
                ("capacite", models.PositiveIntegerField(blank=True, null=True)),
                ("adresse", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                ("telephone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("horaires_visite", models.CharField(blank=True, max_length=200)),
                (
                    "conditions_visite",
                    models.TextField(
                        blank=True, help_text="Pièces et objets autorisés, consignes pratiques."
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "direction_regionale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="etablissements",
                        to="referentiels.directionregionale",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="etablissements",
                        to="referentiels.region",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="etablissements",
                        to="referentiels.typeetablissement",
                    ),
                ),
            ],
            options={
                "db_table": "etablissements",
                "ordering": ["nom"],
            },
            managers=[
                ("objets", django.db.models.manager.Manager()),
            ],
        ),
    ]
