# Generated by Django 5.1.15 on 2026-07-27 11:32

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models

import apps.concours.models
import core.id


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Concours",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("supprime_le", models.DateTimeField(blank=True, editable=False, null=True)),
                ("titre", models.CharField(max_length=200)),
                ("code", models.SlugField(max_length=80, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "conditions",
                    models.TextField(blank=True, help_text="Conditions d'accès, pièces exigées."),
                ),
                (
                    "frais_inscription",
                    models.DecimalField(
                        decimal_places=0, default=0, help_text="Montant en FCFA.", max_digits=10
                    ),
                ),
                ("date_ouverture", models.DateField()),
                ("date_cloture", models.DateField()),
                ("date_concours", models.DateField(blank=True, null=True)),
                ("places_disponibles", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("OUVERT", "Ouvert"),
                            ("CLOTURE", "Clôturé"),
                            ("RESULTATS_PUBLIES", "Résultats publiés"),
                        ],
                        default="BROUILLON",
                        max_length=20,
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Concours",
                "db_table": "concours",
                "ordering": ["-date_ouverture"],
            },
            managers=[
                ("objets", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Candidature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("supprime_le", models.DateTimeField(blank=True, editable=False, null=True)),
                ("numero_suivi", models.CharField(editable=False, max_length=30, unique=True)),
                ("code_suivi", models.CharField(editable=False, max_length=10)),
                ("candidat_nom", models.CharField(max_length=150)),
                ("candidat_prenom", models.CharField(max_length=150)),
                ("candidat_email", models.EmailField(max_length=254)),
                ("candidat_telephone", models.CharField(max_length=30)),
                ("niveau_etude", models.CharField(blank=True, max_length=150)),
                ("experience", models.TextField(blank=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("SOUMISE", "Soumise"),
                            ("EN_INSTRUCTION", "En instruction"),
                            ("PIECES_MANQUANTES", "Pièces manquantes"),
                            ("ADMISSIBLE", "Admissible"),
                            ("CONVOQUE", "Convoqué"),
                            ("ADMIS", "Admis"),
                            ("REJETE", "Rejeté"),
                        ],
                        default="SOUMISE",
                        max_length=20,
                    ),
                ),
                ("motif_rejet", models.TextField(blank=True)),
                ("date_instruction", models.DateTimeField(blank=True, null=True)),
                (
                    "cle_idempotence",
                    models.CharField(blank=True, max_length=80, null=True, unique=True),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instructeur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "concours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidatures",
                        to="concours.concours",
                    ),
                ),
            ],
            options={
                "db_table": "candidatures",
                "ordering": ["-cree_le"],
            },
            managers=[
                ("objets", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ConvocationCandidature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "numero_convocation",
                    models.CharField(editable=False, max_length=40, unique=True),
                ),
                (
                    "charge_qr_jws",
                    models.TextField(
                        editable=False, help_text="Charge signée (JWS) encodée dans le QR."
                    ),
                ),
                ("lieu", models.CharField(blank=True, max_length=200)),
                ("date_convocation", models.DateTimeField()),
                (
                    "candidature",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="convocation",
                        to="concours.candidature",
                    ),
                ),
            ],
            options={
                "db_table": "convocations_candidature",
                "ordering": ["-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="PieceJointeCandidature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.id.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "type_piece",
                    models.CharField(
                        choices=[
                            ("CV", "Curriculum vitae"),
                            ("DIPLOME", "Diplôme"),
                            ("ATTESTATION", "Attestation"),
                            ("AUTRE", "Autre document"),
                        ],
                        max_length=30,
                    ),
                ),
                ("fichier", models.FileField(upload_to=apps.concours.models.chemin_piece_jointe)),
                ("empreinte_sha256", models.CharField(blank=True, editable=False, max_length=64)),
                (
                    "statut_controle",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente de contrôle"),
                            ("LISIBLE", "Lisible"),
                            ("ILLISIBLE", "Illisible — à representer"),
                        ],
                        default="EN_ATTENTE",
                        max_length=20,
                    ),
                ),
                (
                    "candidature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pieces",
                        to="concours.candidature",
                    ),
                ),
            ],
            options={
                "db_table": "pieces_jointes_candidature",
                "ordering": ["-cree_le"],
            },
        ),
    ]
