# Generated by Django 5.1.15 on 2026-07-27 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concours", "0001_initial"),
        ("mediatheque", "0004_remove_documentpublic_fichier_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="concours",
            name="document_avis",
            field=models.ForeignKey(
                blank=True,
                help_text="Avis officiel (PDF) publié dans les documents officiels — visible sur l'accueil.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="concours",
                to="mediatheque.documentpublic",
            ),
        ),
    ]
